### ISSUE TITLE
Error: Cannot find module './core' error after updating to Meteor 1.4.2

### ISSUE THREAD

**Issue by zcrowe** [p-j/meteor-crypto-hmac#2]
Hello I've been using this module with great results for some time!  After upgrading to Metoer 1.4.2 I'm getting this error during startup: Error: Cannot find module './core' error

Is this easilly resolved?

**Comment by p-j** [comment]
Hi, 
I have no idea, I haven't used meteor in a while so I'd have to take some time to investigate the change in Meteor 1.4.2 that might cause that.

Can you tell me from what version were you upgrading from ?

**Comment by p-j** [comment]
Can you make sure https://github.com/p-j/meteor-crypto-core is installed as a dependency ?

**Comment by zcrowe** [comment]
Thanks for the reply 👍 

Yep,  i have the dependecy installed - I upgraded from 1.4.1.2.

**Comment by p-j** [comment]
Hi @zcrowe I don't think I'll have time to look into this issue before this week-end. In the mean time, could you share the full stacktrace and maybe setup a small repo that reproduce the the error with a minimal setup ? That would help greatly :)

**Comment by zcrowe** [comment]
Dude - do not sweat it, it turns out I am simply an idiot.

In trying ot get this to work in an earlier itteration, I had a different 'core crypto' lib installed as well the the suggested by yourself. The 'other' lib superceded the proper one and was the thing having an issue after update.  Removing it made everythign work - sorry for the false alarm :)

**Comment by p-j** [comment]
Happy to hear you sorted it out :)
